apiVersion: v2
name: opensearch
description: A Helm chart for OpenSearch
version: 13.0.0
appVersion: "2.x" # Assuming OpenSearch 2.x
dependencies:
  - name: opensearch
    version: "2.x.x" # Use a stable version of OpenSearch chart
    repository: "https://opensearch-project.github.io/helm-charts/"
