apiVersion: v1
kind: Service
metadata:
  name: {{ include "model-router.fullname" . }}
  labels:
    {{- include "model-router.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 11434 # Ollama default port
      targetPort: ollama-http
      protocol: TCP
      name: ollama-http
  selector:
    {{- include "model-router.selectorLabels" . | nindent 4 }}
