apiVersion: v1
kind: Secret
metadata:
  name: {{ include "predator-app.fullname" . }}
type: Opaque
stringData:
  minioAccessKey: {{ .Values.env.MINIO_ACCESS_KEY | quote }}
  minioSecretKey: {{ .Values.env.MINIO_SECRET_KEY | quote }}
