apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.secretsRef.name }}
  labels:
    app.kubernetes.io/name: predator-umbrella
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data: {}
