{{- if .Values.pdb.enabled -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "predator-umbrella.fullname" . }}
  labels:
    app.kubernetes.io/name: predator-umbrella
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: predator-umbrella
      app.kubernetes.io/instance: {{ .Release.Name }}
{{- end -}}
