{{- if .Values.pdb.enabled -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "predator-umbrella.fullname" . }}
  labels:
    {{- include "predator-umbrella.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "predator-umbrella.selectorLabels" . | nindent 6 }}
{{- end -}}
